dashboard/urls.py
#coding: utf-8
from django.conf.urls import url

from .views import dashboard

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
]

funcionarios/urls.py
#coding: utf-8
from django.conf.urls import url

from .views import novo_funcionario, lista_funcionarios, editar_funcionario

urlpatterns = [
    url(r'^$', lista_funcionarios, name='lista_funcionarios'),
    url(r'^novo/$', novo_funcionario, name='novo_funcionario'),
    url(r'^(?P<pk>\d+)/editar/$', editar_funcionario, name='editar_funcionario'),
]

timesheet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout_then_login, login


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, {"template_name": 'dashboard/login.html'}, name='login'),
    url(r'^logout/', logout_then_login, {'login_url': '/'}, name='logout'),
    

    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^funcionarios/', include('funcionarios.urls', namespace='funcionarios')),
    url(r'^tomadores/', include('tomadores.urls', namespace='tomadores')),
]

tomadores/urls.py
#coding: utf-8
from django.conf.urls import url

from .views import novo_tomador, lista_tomadores, editar_tomador

urlpatterns = [
    url(r'^$', lista_tomadores, name='lista_tomadores'),
    url(r'^novo/$', novo_tomador, name='novo_tomador'),
    url(r'^(?P<pk>\d+)/editar/$', editar_tomador, name='editar_tomador'),
]

dashboard/models.py
from django.db import models

# Create your models here.

funcionarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Funcionario(models.Model):
    nome = models.CharField(max_length=255)
    data_admissao = models.DateField()
    SEXO_CHOICE = (
        ('m','Masculino'),
        ('f','Feminino'),
    )
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICE)
    email = models.EmailField()
    

tomadores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Tomador(models.Model):
    nome = models.CharField(max_length=255)    
    

funcionarios/forms.py
from django import forms
from .models import Funcionario

class FuncionarioForm(forms.ModelForm):

    class Meta:
        model = Funcionario
        fields = ['nome','data_admissao','sexo','email']

tomadores/forms.py
from django import forms
from .models import Tomador

class TomadorForm(forms.ModelForm):

    class Meta:
        model = Tomador
        fields = ['nome']

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def dashboard(request):
	return render(request, 'dashboard/index.html')

funcionarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import CreateView

from .forms import FuncionarioForm
from .models import Funcionario

def lista_funcionarios(request):
    funcionarios = Funcionario.objects.all()
    return render(request, 'funcionarios/lista.html', 
        {'funcionarios':funcionarios })

# class FuncionarioCreateView(CreateView):
#     form_class = FuncionarioForm
#     template_name = 'funcionarios/novo.html'
#     success_url = reverse_lazy('funcionarios:lista_funcionarios')
    
def novo_funcionario(request):

    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse('funcionarios:lista_funcionarios'))
    else:
        form = FuncionarioForm()

    return render(request, 
        'funcionarios/novo.html', {'form':form})

def editar_funcionario(request, pk):
    funcionario = Funcionario.objects.get(pk=pk)
    if request.method == 'POST':
        form = FuncionarioForm(request.POST, instance=funcionario)
        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse('funcionarios:lista_funcionarios'))
    else:
        form = FuncionarioForm(instance=funcionario)

    return render(request, 
        'funcionarios/editar.html', {'form':form})

tomadores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect

from .forms import TomadorForm
from .models import Tomador


def novo_tomador(request):
    if request.method == 'POST':
        form = TomadorForm(request.POST)
        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse('tomadores:lista_tomadores'))
    else:
        form = TomadorForm()

    return render(request
    	, 'tomadores/novo.html'
    	, {'form':form} 
    )

def lista_tomadores(request):
    tomadores = Tomador.objects.all()
    return render(request, 'tomadores/lista.html', 
        {'tomadores':tomadores })

def editar_tomador(request, pk):
    tomador = Tomador.objects.get(pk=pk)
    if request.method == 'POST':
        form = TomadorForm(request.POST, instance=tomador)
        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse('tomadores:lista_tomadores'))
    else:
        form = TomadorForm(instance=tomador)

    return render(request, 
        'tomadores/editar.html', {'form':form})

dashboard/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

{% include 'dashboard/includes/header.html' %}

<body>
    <div id="wrapper">
    	<main id="content">
        	{% include 'dashboard/includes/menu.html' %}
        	<div id="page-wrapper" class="gray-bg dashbard-1">
	            {% if request.user.is_authenticated %}
                    <div class="row border-bottom">
    	                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    	                <div class="navbar-header">
    	                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
    <!-- 	                    <form role="search" class="navbar-form-custom" action="search_results.html">
    	                        <div class="form-group">
    	                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
    	                        </div>
    	                    </form> -->
    	                </div>
    	                    {% include 'dashboard/includes/notifications.html' %}
    	                </nav>
    	            </div>
                {% endif %}
	            <div id="wrapper">
	        		{% block content %}
	        		{% endblock %}
	        		<div class="footer">
				        <div>
				            <strong>Copyright</strong> Projeto &copy; 2016
				        </div>
				    </div>
	        	</div>
        	</div>
        </main>

    </div>
    
   {% include 'dashboard/includes/footer.html' %}
</body>
</html>

dashboard/templates/dashboard/editar.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Editar Usuário</h2>
        <ol class="breadcrumb">
            <li>
                <a href="">Home</a>
            </li>
            <li>
                <a href="">Usuários</a>
            </li>
            <li class="active">
                <strong>Editar Usuário</strong>
            </li>
        </ol>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Editar Usuário</h5>
                </div>
                <div class="ibox-content">
                    <form method="POST" class="form-horizontal", enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ field.label }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            {% if field.name == 'photo' and form.instance.photo %}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Foto Atual</label>
                                    <div class="col-sm-10"><a href="{{form.instance.photo.url}}">{{ form.instance.photo }}</a></div>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-7 col-sm-offset-9">
                                <button class="btn btn-white" onclick="goBack()">Cancel</button>
                                <button class="btn btn-primary" type="submit">Save changes</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

dashboard/templates/dashboard/includes/footer.html
 {% load staticfiles %}
 <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <!-- Flot -->
    <script src="{% static 'js/plugins/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.spline.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.pie.js' %}"></script>

    <!-- Peity -->
    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>
    <script src="{% static 'js/demo/peity-demo.js' %}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>

    <!-- jQuery UI -->
    <script src="{% static 'js/plugins/jquery-ui/jquery-ui.min.js' %}"></script>

    <!-- GITTER -->
    <script src="{% static 'js/plugins/gritter/jquery.gritter.min.js' %}"></script>

    <!-- Sparkline -->
    <script src="{% static 'js/plugins/sparkline/jquery.sparkline.min.js' %}"></script>

    <!-- Sparkline demo data  -->
    <script src="{% static 'js/demo/sparkline-demo.js' %}"></script>

    <!-- ChartJS-->
    <script src="{% static 'js/plugins/chartJs/Chart.min.js' %}"></script>

    <!-- Toastr -->
    <script src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>



<!--     <script src="{% static 'dashboard/js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/jeditable/jquery.jeditable.js' %}"></script>

    <script src="{% static 'dashboard/js/plugins/dataTables/datatables.min.js' %}"></script>

    
    <script src="{% static 'dashboard/js/inspinia.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/pace/pace.min.js' %}"></script> -->

    <script>
        $(document).ready(function() {
            // setTimeout(function() {
            //     toastr.options = {
            //         closeButton: true,
            //         progressBar: true,
            //         showMethod: 'slideDown',
            //         timeOut: 4000
            //     };
            //     toastr.success('Responsive Admin Theme', 'Welcome to INSPINIA');

            // }, 1300);


            var data1 = [
                [0,4],[1,8],[2,5],[3,10],[4,4],[5,16],[6,5],[7,11],[8,6],[9,11],[10,30],[11,10],[12,13],[13,4],[14,3],[15,3],[16,6]
            ];
            var data2 = [
                [0,1],[1,0],[2,2],[3,0],[4,1],[5,3],[6,1],[7,5],[8,2],[9,3],[10,2],[11,1],[12,0],[13,2],[14,8],[15,0],[16,0]
            ];
            $("#flot-dashboard-chart").length && $.plot($("#flot-dashboard-chart"), [
                data1, data2
            ],
                    {
                        series: {
                            lines: {
                                show: false,
                                fill: true
                            },
                            splines: {
                                show: true,
                                tension: 0.4,
                                lineWidth: 1,
                                fill: 0.4
                            },
                            points: {
                                radius: 0,
                                show: true
                            },
                            shadowSize: 2
                        },
                        grid: {
                            hoverable: true,
                            clickable: true,
                            tickColor: "#d5d5d5",
                            borderWidth: 1,
                            color: '#d5d5d5'
                        },
                        colors: ["#1ab394", "#1C84C6"],
                        xaxis:{
                        },
                        yaxis: {
                            ticks: 4
                        },
                        tooltip: false
                    }
            );

            var doughnutData = [
                {
                    value: 300,
                    color: "#a3e1d4",
                    highlight: "#1ab394",
                    label: "App"
                },
                {
                    value: 50,
                    color: "#dedede",
                    highlight: "#1ab394",
                    label: "Software"
                },
                {
                    value: 100,
                    color: "#A4CEE8",
                    highlight: "#1ab394",
                    label: "Laptop"
                }
            ];

            var doughnutOptions = {
                segmentShowStroke: true,
                segmentStrokeColor: "#fff",
                segmentStrokeWidth: 2,
                percentageInnerCutout: 45, // This is 0 for Pie charts
                animationSteps: 100,
                animationEasing: "easeOutBounce",
                animateRotate: true,
                animateScale: false
            };

            var ctx = document.getElementById("doughnutChart").getContext("2d");
            var DoughnutChart = new Chart(ctx).Doughnut(doughnutData, doughnutOptions);

            var polarData = [
                {
                    value: 300,
                    color: "#a3e1d4",
                    highlight: "#1ab394",
                    label: "App"
                },
                {
                    value: 140,
                    color: "#dedede",
                    highlight: "#1ab394",
                    label: "Software"
                },
                {
                    value: 200,
                    color: "#A4CEE8",
                    highlight: "#1ab394",
                    label: "Laptop"
                }
            ];

            var polarOptions = {
                scaleShowLabelBackdrop: true,
                scaleBackdropColor: "rgba(255,255,255,0.75)",
                scaleBeginAtZero: true,
                scaleBackdropPaddingY: 1,
                scaleBackdropPaddingX: 1,
                scaleShowLine: true,
                segmentShowStroke: true,
                segmentStrokeColor: "#fff",
                segmentStrokeWidth: 2,
                animationSteps: 100,
                animationEasing: "easeOutBounce",
                animateRotate: true,
                animateScale: false
            };
            var ctx = document.getElementById("polarChart").getContext("2d");
            var Polarchart = new Chart(ctx).PolarArea(polarData, polarOptions);

        });

         function goBack() {
            window.history.back();
        }
    </script>

dashboard/templates/dashboard/includes/header.html
{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Projeto | Dashboard</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <!-- Toastr style -->
    <link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

    <!-- Gritter -->
    <link href="{% static 'js/plugins/gritter/jquery.gritter.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

dashboard/templates/dashboard/includes/notifications.html
{% load staticfiles %}  

<ul class="nav navbar-top-links navbar-right">
    <li>
        <span class="m-r-sm text-muted welcome-message">Bem vindo!</span>
    </li>
    <li>
        <a href="{% url 'logout' %}">
            <i class="fa fa-sign-out"></i> Log out
        </a>
    </li>
</ul>

dashboard/templates/dashboard/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row border-bottom white-bg dashboard-header">
        <div class="col-sm-4">
            <h2>Bem vindo {{ request.user.name }}</h2>
            <small>Projeto</i></small>
        </div>
    </div>

{% endblock %}

dashboard/templates/dashboard/lista.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Listagem de Usuários</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'dashboard:dashboard' %}">Home</a>
            </li>
            <li class="active">
                <strong>Usuários</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Listagem de funcionários</h5>

                    <div class="ibox-tools">
                        <a class="collapse-link" href="">
                            <strong><i class="fa fa-plus"></i> Funcionário</strong>
                        </a>

                    </div>
                </div>
                <div class="ibox-content">

                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" >
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Email</th>
                                    <th>Celular</th>
                                    <th>Cargo</th>
                                    <th>Editar</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for person in people_list %}
                                    <tr class="gradeX">
                                        <td class="col-lg-3">{{ person.name }}</td>
                                        <td class="col-lg-3">{{ person.email }}</td>
                                        <td class="col-lg-3">{{ person.cellphone }}</td>
                                        <td class="col-lg-3">{{ person.get_function_display }}</td>
                                        <td class="col-lg-1 center">
                                            <center>
                                                <a href=""><i class="fa fa-wrench"></i></a>
                                            </center>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th>Email</th>
                                    <th>Celular</th>
                                    <th>Cargo</th>
                                    <th>Editar</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

funcionarios/templates/funcionarios/lista.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Listagem de Funcionários</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'dashboard:dashboard' %}">Home</a>
            </li>
            <li class="active">
                <strong>Funcionários</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Listagem de Funcionários</h5>

                    <div class="ibox-tools">
                        <a class="collapse-link" href="{% url 'funcionarios:novo_funcionario' %}">
                            <strong><i class="fa fa-plus"></i> Funcionário</strong>
                        </a>

                    </div>
                </div>
                <div class="ibox-content">

                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" >
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Data de Admissão</th>
                                    <th>Sexo</th>
                                    <th>Email</th>
                                    <th>Editar</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for funcionario in funcionarios %}
                                    <tr class="gradeX">
                                        <td class="col-lg-3">{{ funcionario.nome }}</td>
                                        <td class="col-lg-3">{{ funcionario.data_admissao|date:"SHORT_DATE_FORMAT" }}</td>
                                        <td class="col-lg-3">{{ funcionario.get_sexo_display }}</td>
                                        <td class="col-lg-3">{{ funcionario.email }}</td>
                                        <td class="col-lg-1 center">
                                            <center>
                                                <a href="{% url 'funcionarios:editar_funcionario' pk=funcionario.pk %}"><i class="fa fa-wrench"></i></a>
                                            </center>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th>Data de Admissão</th>
                                    <th>Sexo</th>
                                    <th>Email</th>
                                    <th>Editar</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

funcionarios/templates/funcionarios/novo.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Novo Funcionário</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'dashboard:dashboard' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'funcionarios:lista_funcionarios' %}">Funcionários</a>
            </li>
            <li class="active">
                <strong>Novo Funcionário</strong>
            </li>
        </ol>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Novo Usuário</h5>
                </div>
                <div class="ibox-content">
                    <form method="POST" class="form-horizontal", enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ field.label }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                            <div class="hr-line-dashed"></div>
                        {% endfor %}
                            <div class="form-group">
                                <div class="col-sm-7 col-sm-offset-9">
                                    <button class="btn btn-white" onclick="goBack()">Cancel</button>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tomadores/templates/tomadores/lista.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Listagem de Tomadores</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'dashboard:dashboard' %}">Home</a>
            </li>
            <li class="active">
                <strong>Tomadores</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Listagem de Tomadores</h5>

                    <div class="ibox-tools">
                        <a class="collapse-link" href="{% url 'tomadores:novo_tomador' %}">
                            <strong><i class="fa fa-plus"></i> Tomador</strong>
                        </a>

                    </div>
                </div>
                <div class="ibox-content">

                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" >
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Editar</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for tomador in tomadores %}
                                    <tr class="gradeX">
                                        <td class="col-lg-10">{{ tomador.nome }}</td>
                                        <td class="col-lg-2 center">
                                            <center>
                                                <a href="{% url 'tomadores:editar_tomador' pk=tomador.pk %}"><i class="fa fa-wrench"></i></a>
                                            </center>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            {% if tomadores.count >= 3 %}
                            <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th>Editar</th>
                                </tr>
                            </tfoot>
                            {% endif %}
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tomadores/templates/tomadores/novo.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Novo Tomador</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'dashboard:dashboard' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'tomadores:lista_tomadores' %}">Tomadores</a>
            </li>
            <li class="active">
                <strong>Novo Tomador</strong>
            </li>
        </ol>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Novo Tomador</h5>
                </div>
                <div class="ibox-content">
                    <form method="POST" class="form-horizontal", enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ field.label }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                            <div class="hr-line-dashed"></div>
                        {% endfor %}
                            <div class="form-group">
                                <div class="col-sm-7 col-sm-offset-9">
                                    <button class="btn btn-white" onclick="goBack()">Cancel</button>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}